main/objects/API_Dummy__c/API_Dummy__c.object-meta.xml
<CustomObject>
    <label>API Dummy</label>
    <nameField>
        <label>API Dummy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Dummies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/objects/API_Dummy__c/fields/Calllout_Auth_Type__c.field-meta.xml
<CustomField>
    <fullName>Calllout_Auth_Type__c</fullName>
    <label>Calllout Auth Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Basic authentication</fullName>
            </value>
            <value>
                <fullName>OAuth 2.0</fullName>
            </value>
            <value>
                <fullName>Bearer token</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/objects/API_Dummy__c/fields/Callout_Body__c.field-meta.xml
<CustomField>
    <fullName>Callout_Body__c</fullName>
    <label>Callout Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/objects/API_Dummy__c/fields/Callout_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Callout_Client_ID__c</fullName>
    <label>Callout Client ID</label>
    <type>TextArea</type>
</CustomField>

main/objects/API_Dummy__c/fields/Callout_Client_secreat__c.field-meta.xml
<CustomField>
    <fullName>Callout_Client_secreat__c</fullName>
    <label>Callout Client secreat</label>
    <type>TextArea</type>
</CustomField>

main/objects/API_Dummy__c/fields/Callout_Grant_type__c.field-meta.xml
<CustomField>
    <fullName>Callout_Grant_type__c</fullName>
    <label>Callout Grant type</label>
    <type>TextArea</type>
</CustomField>

main/objects/API_Dummy__c/fields/Callout_Method__c.field-meta.xml
<CustomField>
    <fullName>Callout_Method__c</fullName>
    <label>Callout Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/objects/API_Dummy__c/fields/Callout_Password__c.field-meta.xml
<CustomField>
    <fullName>Callout_Password__c</fullName>
    <label>Callout Password</label>
    <type>TextArea</type>
</CustomField>

main/objects/API_Dummy__c/fields/Callout_Request_Time__c.field-meta.xml
<CustomField>
    <fullName>Callout_Request_Time__c</fullName>
    <label>Callout Request Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/objects/API_Dummy__c/fields/Callout_Respose_Time__c.field-meta.xml
<CustomField>
    <fullName>Callout_Respose_Time__c</fullName>
    <label>Callout Respose Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/objects/API_Dummy__c/fields/Callout_Time_Diff__c.field-meta.xml
<CustomField>
    <fullName>Callout_Time_Diff__c</fullName>
    <formula>Diff_Filed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Callout Time Diff</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/objects/API_Dummy__c/fields/Callout_Token__c.field-meta.xml
<CustomField>
    <fullName>Callout_Token__c</fullName>
    <label>Callout Token</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/objects/API_Dummy__c/fields/Callout_UserName__c.field-meta.xml
<CustomField>
    <fullName>Callout_UserName__c</fullName>
    <label>Callout UserName</label>
    <type>TextArea</type>
</CustomField>

main/objects/API_Dummy__c/fields/Diff_Filed__c.field-meta.xml
<CustomField>
    <fullName>Diff_Filed__c</fullName>
    <label>Diff Filed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/objects/API_Dummy__c/fields/EndpointURL__c.field-meta.xml
<CustomField>
    <fullName>EndpointURL__c</fullName>
    <label>EndpointURL</label>
    <type>TextArea</type>
</CustomField>

main/objects/API_Health_Check__c/API_Health_Check__c.object-meta.xml
<CustomObject>
    <label>API Health Check</label>
    <nameField>
        <displayFormat>API-{YY}{MM}{DD}-{000000}</displayFormat>
        <label>API Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Health Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/objects/API_Health_Check__c/fields/Callout_Response__c.field-meta.xml
<CustomField>
    <fullName>Callout_Response__c</fullName>
    <label>Callout Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/objects/API_Health_Check__c/fields/Callout_Time_Difference__c.field-meta.xml
<CustomField>
    <fullName>Callout_Time_Difference__c</fullName>
    <formula>Differenec_field__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Callout Time Difference</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/objects/API_Health_Check__c/fields/Differenec_field__c.field-meta.xml
<CustomField>
    <fullName>Differenec_field__c</fullName>
    <label>Differenec field</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/objects/API_Health_Check__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <type>TextArea</type>
</CustomField>

main/objects/API_Health_Check__c/fields/Final_Time__c.field-meta.xml
<CustomField>
    <fullName>Final_Time__c</fullName>
    <label>Final Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/objects/API_Health_Check__c/fields/Initial_Time__c.field-meta.xml
<CustomField>
    <fullName>Initial_Time__c</fullName>
    <label>Initial Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/classes/ApiCalloutController.cls
/**
 * @ Author: Clueless Coders
 * @ Create Time: 09/12/2023
 * @ Modified by: Your name
 * @ Modified time: 09/12/2023
 * @ Description: Apex method to perform HTTP callouts
 */

public class ApiCalloutController {

//Generate new access token from user credentials
    @AuraEnabled
    public static string generateNewAccessToken(String header,String accessTokenUrl){

        HTTP http = new HTTP();
        HttpRequest request = new HttpRequest();
        request.setMethod('POST');
        request.setEndpoint(accessTokenUrl);

        String jsonBodyString = APICalloutController.getBodyString(header);
        request.setBody(jsonBodyString);
        HttpResponse response = HTTP.send(request);
        String finalResponse = response.getStatusCode() +' '+  response.getStatus() + response.getBody();
        return finalResponse;
    }

    @AuraEnabled
    public static string generateBearerToken(String EndPointUrl,String body){
        System.debug('EndPointUrl'+EndPointUrl);
        System.debug('body'+body);
        HTTP http = new HTTP();
        HttpRequest request = new HttpRequest();
        request.setMethod('POST');
        request.setEndpoint(EndPointUrl);
        String jsonBodyString = APICalloutController.getBodyString(body);
        request.setBody(jsonBodyString);
        Long startTime = DateTime.now().getTime();
        HttpResponse response = HTTP.send(request);
        Long endTime = DateTime.now().getTime();
        String finalResponse = response.getBody();
        Double timeDiff = TimeDiff.getTimeDifference(startTime,endTime);
        System.debug('timeDiff'+timeDiff);
        System.debug('finalResponse===>'+finalResponse);
        return finalResponse;
    }
//Create body string

    public static String getBodyString(String body){
        
        Map<String, Object> bodyMap = (Map<String, Object>)JSON.deserializeUntyped(body);
        String jsonBodyString = '';
        if(bodyMap.size()>0){
            Set <String> bodyKeys = new Set <String>();
            bodyKeys = bodyMap.keySet();
            List<String> keyList = new List<String>(bodyKeys);
            jsonBodyString = keyList[0] + '=' + bodyMap.get(keyList[0]);
            if(bodyMap.size()>1){
                for(Integer i=1;i<keyList.size();i++){
                    jsonBodyString = jsonBodyString + '&' + keyList[i] + '=' + bodyMap.get(keyList[i]);
                }
            }
        }
        return jsonBodyString;
    }


//HTTP callout to get response

    @AuraEnabled
    public static String httpCallout(String inputs,String header) {

        Map<String, Object> inputparamsMap = (Map<String, Object>)JSON.deserializeUntyped(inputs);
        Map<String, Object> headerMap = (Map<String, Object>)JSON.deserializeUntyped(header);

        API_Dummy__c apiDummy = new API_Dummy__c ();

        String endpoint = String.valueOf(inputparamsMap.get('url'));
        String authType = String.valueOf(inputparamsMap.get('auth'));
        String method = String.valueOf(inputparamsMap.get('method'));
        String token = String.valueOf(inputparamsMap.get('token'));
        String body = String.valueOf(inputparamsMap.get('body'));

        apiDummy.EndpointURL__c = endpoint;
        if(authType != 'None')
        {
            apiDummy.Calllout_Auth_Type__c = authType;
        }
        else {
            apiDummy.Calllout_Auth_Type__c = 'N/A';
        }
        apiDummy.Callout_Method__c = method;

        Http http = new HTTP();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(endpoint);
        request.setMethod(method);
		if(method != 'GET')
        {
            if(headerMap.size()>0){
                String jsonBodyString = ApiCalloutController.getBodyString(header);
                apiDummy.Callout_Body__c = jsonBodyString;
                request.setBody(jsonBodyString);
        	}

            if(body!=null){
                String jsonBodyString = ApiCalloutController.getBodyString(body);
                apiDummy.Callout_Body__c = jsonBodyString;
                request.setBody(jsonBodyString);
            }
        }
        if(token!=null){
            String access_token = token;
            apiDummy.Callout_Token__c = access_token;
            request.setHeader('Authorization', 'Bearer ' + access_token);
        }

        if(authType == 'Basic authentication'){
            String username = String.valueOf(headerMap.get('username'));
            String password = String.valueOf(headerMap.get('password'));
            Blob headerValue = Blob.valueOf(username + ':' + password);
            String authorizationHeader = 'BASIC ' +EncodingUtil.base64Encode(headerValue);
            request.setHeader('Authorization', authorizationHeader);

            apiDummy.Callout_UserName__c = username;
            apiDummy.Callout_Password__c = password;
            
        }
        Long startTime = DateTime.now().getTime();
        HttpResponse response = http.send(request);
        Long endTime = DateTime.now().getTime();

        apiDummy.Callout_Request_Time__c = startTime;
        apiDummy.Callout_Respose_Time__c = endTime;
        apiDummy.Diff_Filed__c = TimeDiff.getTimeDifference(startTime,endTime);

        String finalResponse = response.getStatusCode() +' '+ response.getStatus() + response.getBody();
        //apiDummy.Callout_Response__c = finalResponse;
        System.debug('apiDummy===>'+apiDummy);
        insert apiDummy;
        return finalResponse;  
    }


//HTTP callout to create new resource

    @AuraEnabled
    public static string createNewResource(String token,String body,String endPointUrl){
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(endPointUrl);
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        request.setBody(body);
        request.setHeader('Authorization', 'Bearer ' + token);
        HttpResponse response = http.send(request);
        String finalResponse = response.getStatusCode() +' '+  response.getStatus() + response.getBody();
        return finalResponse;
    }

    @AuraEnabled
    public static void getApiRecords() {
        List<API_Dummy__c> listOfApiDummi = [SELECT Id,EndpointURL__c, Callout_Method__c, Callout_Body__c, Callout_Password__c, Callout_UserName__c, Callout_Request_Time__c, Callout_Response__c, Callout_Time_Diff__c, Callout_Grant_type__c, Callout_Token__c, Callout_Client_secreat__c, Callout_Client_ID__c, Calllout_Auth_Type__c  FROM API_Dummy__c];
        System.debug('listOfApiDummi=====>'+listOfApiDummi);
        for (API_Dummy__c apiDumy : listOfApiDummi) {

            Http http = new HTTP();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(apiDumy.EndpointURL__c);
            request.setMethod(apiDumy.Callout_Method__c);
            if(apiDumy.Callout_Body__c != null || apiDumy.Callout_Body__c == '')
            {
                request.setBody(apiDumy.Callout_Body__c);
            }
            request.setHeader('Authorization', 'Bearer ' + apiDumy.Callout_Token__c);

            if(apiDumy.Calllout_Auth_Type__c == 'Basic authentication') {
                Blob headerValue = Blob.valueOf(apiDumy.Callout_UserName__c + ':' + apiDumy.Callout_Password__c);
                String authorizationHeader = 'BASIC ' +EncodingUtil.base64Encode(headerValue);
                request.setHeader('Authorization', authorizationHeader);
            }
            Long startTime = DateTime.now().getTime();
            Long endTime;
            HttpResponse response = http.send(request);
            if(response != null)
            {
                endTime = DateTime.now().getTime();
            }
            Double timeDiff = TimeDiff.getTimeDifference(startTime,endTime);
            String finalResponse = response.getStatusCode() +' '+ response.getStatus() + response.getBody();
            System.debug('runCheckCalloutMethod===>finalResponse===>'+finalResponse);
            API_Health_Check__c apiHealthCheck = new API_Health_Check__c();
            apiHealthCheck.Endpoint__c = apiDumy.EndpointURL__c;
            apiHealthCheck.Callout_Response__c = finalResponse;
            apiHealthCheck.Initial_Time__c = startTime;
            apiHealthCheck.Final_Time__c = endTime;
            apiHealthCheck.Differenec_field__c = timeDiff;
            insert apiHealthCheck;
            System.debug('apiHealthCheck====>'+apiHealthCheck);
        }
    }   
    @AuraEnabled
    public static List<API_Health_Check__c> getRecords(){
        return [SELECT Id, Name, Callout_Method__c,Callout_Response__c,Callout_Time_Difference__c,Differenec_field__c,Endpoint__c FROM API_Health_Check__c LIMIT 5];
    }
}